[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "8"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    # Content Security Policy
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 'unsafe-inline' https://cdnjs.cloudflare.com;
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://fonts.gstatic.com;
      font-src 'self' https://fonts.googleapis.com https://fonts.gstatic.com;
      img-src 'self' data: https:;
      connect-src 'self' https:;
      frame-ancestors 'none';
      base-uri 'self';
      form-action 'self';
    """
    # Additional security headers
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    Permissions-Policy = "camera=(), microphone=(), geolocation=(), payment=()"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache fonts
[[headers]]
  for = "/*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Security for API endpoints (if any)
[[headers]]
  for = "/api/*"
  [headers.values]
    X-Robots-Tag = "noindex"
    X-Frame-Options = "DENY"

# Redirects for security
[[redirects]]
  from = "/.well-known/security.txt"
  to = "/security.txt"
  status = 301

# Redirect HTTP to HTTPS
[[redirects]]
  from = "http://secureweb3-pro.netlify.app/*"
  to = "https://secureweb3-pro.netlify.app/:splat"
  status = 301
  force = true

# 404 page
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

# Rate limiting (if available)
[context.production]
  [context.production.environment]
    RATE_LIMIT = "100"
    ENVIRONMENT = "production"

[context.deploy-preview]
  [context.deploy-preview.environment]
    ENVIRONMENT = "preview"

[context.branch-deploy]
  [context.branch-deploy.environment]
    ENVIRONMENT = "development"

# Edge functions for enhanced security (if needed)
[[edge_functions]]
  function = "security-headers"
  path = "/*"

# Form handling with spam protection
[forms]
  [forms.settings]
    protected = true

# Plugin configuration
[[plugins]]
  package = "@netlify/plugin-lighthouse"
  
  [plugins.inputs]
    output_path = "reports/lighthouse"
    
[[plugins]]
  package = "netlify-plugin-a11y"
  
  [plugins.inputs]
    checkPaths = ['/']
    
[[plugins]]
  package = "netlify-plugin-sitemap"
  
  [plugins.inputs]
    buildDir = "dist"
